# Generated by Django 6.0.3 on 2026-04-07 11:36

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_otp_code_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='encrypted_info',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
            preserve_default=False,
        ),
    ]
